/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/letterV.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.V.geometry} material={materials['0057D0']} position={[2, 0.01, -2]} />
    </group>
  )
}

useGLTF.preload('/letterV.gltf')
