/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/letterE.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.E.geometry} material={materials['0057D0']} position={[4, 0, -6]} />
    </group>
  )
}

useGLTF.preload('/letterE.gltf')
